/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResetOtpRouteImport } from './routes/reset-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVoiceNotesRouteImport } from './routes/app.voice-notes'
import { Route as AppStudyBuddyRouteImport } from './routes/app.study-buddy'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppPdfSummarizerRouteImport } from './routes/app.pdf-summarizer'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMindMapRouteImport } from './routes/app.mind-map'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppChallengesRouteImport } from './routes/app.challenges'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetOtpRoute = ResetOtpRouteImport.update({
  id: '/reset-otp',
  path: '/reset-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceNotesRoute = AppVoiceNotesRouteImport.update({
  id: '/voice-notes',
  path: '/voice-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyBuddyRoute = AppStudyBuddyRouteImport.update({
  id: '/study-buddy',
  path: '/study-buddy',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPdfSummarizerRoute = AppPdfSummarizerRouteImport.update({
  id: '/pdf-summarizer',
  path: '/pdf-summarizer',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMindMapRoute = AppMindMapRouteImport.update({
  id: '/mind-map',
  path: '/mind-map',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-otp': typeof ResetOtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mind-map': typeof AppMindMapRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pdf-summarizer': typeof AppPdfSummarizerRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-buddy': typeof AppStudyBuddyRoute
  '/app/voice-notes': typeof AppVoiceNotesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-otp': typeof ResetOtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mind-map': typeof AppMindMapRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pdf-summarizer': typeof AppPdfSummarizerRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-buddy': typeof AppStudyBuddyRoute
  '/app/voice-notes': typeof AppVoiceNotesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-otp': typeof ResetOtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/chat': typeof AppChatRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/mind-map': typeof AppMindMapRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pdf-summarizer': typeof AppPdfSummarizerRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-buddy': typeof AppStudyBuddyRoute
  '/app/voice-notes': typeof AppVoiceNotesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-otp'
    | '/reset-password'
    | '/app/analytics'
    | '/app/challenges'
    | '/app/chat'
    | '/app/flashcards'
    | '/app/leaderboard'
    | '/app/mind-map'
    | '/app/notes'
    | '/app/pdf-summarizer'
    | '/app/planner'
    | '/app/profile'
    | '/app/quiz'
    | '/app/settings'
    | '/app/study-buddy'
    | '/app/voice-notes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-otp'
    | '/reset-password'
    | '/app/analytics'
    | '/app/challenges'
    | '/app/chat'
    | '/app/flashcards'
    | '/app/leaderboard'
    | '/app/mind-map'
    | '/app/notes'
    | '/app/pdf-summarizer'
    | '/app/planner'
    | '/app/profile'
    | '/app/quiz'
    | '/app/settings'
    | '/app/study-buddy'
    | '/app/voice-notes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-otp'
    | '/reset-password'
    | '/app/analytics'
    | '/app/challenges'
    | '/app/chat'
    | '/app/flashcards'
    | '/app/leaderboard'
    | '/app/mind-map'
    | '/app/notes'
    | '/app/pdf-summarizer'
    | '/app/planner'
    | '/app/profile'
    | '/app/quiz'
    | '/app/settings'
    | '/app/study-buddy'
    | '/app/voice-notes'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  RegisterRoute: typeof RegisterRoute
  ResetOtpRoute: typeof ResetOtpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-otp': {
      id: '/reset-otp'
      path: '/reset-otp'
      fullPath: '/reset-otp'
      preLoaderRoute: typeof ResetOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice-notes': {
      id: '/app/voice-notes'
      path: '/voice-notes'
      fullPath: '/app/voice-notes'
      preLoaderRoute: typeof AppVoiceNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-buddy': {
      id: '/app/study-buddy'
      path: '/study-buddy'
      fullPath: '/app/study-buddy'
      preLoaderRoute: typeof AppStudyBuddyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pdf-summarizer': {
      id: '/app/pdf-summarizer'
      path: '/pdf-summarizer'
      fullPath: '/app/pdf-summarizer'
      preLoaderRoute: typeof AppPdfSummarizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mind-map': {
      id: '/app/mind-map'
      path: '/mind-map'
      fullPath: '/app/mind-map'
      preLoaderRoute: typeof AppMindMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/challenges': {
      id: '/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppChatRoute: typeof AppChatRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMindMapRoute: typeof AppMindMapRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPdfSummarizerRoute: typeof AppPdfSummarizerRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuizRoute: typeof AppQuizRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyBuddyRoute: typeof AppStudyBuddyRoute
  AppVoiceNotesRoute: typeof AppVoiceNotesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppChatRoute: AppChatRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMindMapRoute: AppMindMapRoute,
  AppNotesRoute: AppNotesRoute,
  AppPdfSummarizerRoute: AppPdfSummarizerRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuizRoute: AppQuizRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyBuddyRoute: AppStudyBuddyRoute,
  AppVoiceNotesRoute: AppVoiceNotesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  RegisterRoute: RegisterRoute,
  ResetOtpRoute: ResetOtpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
